create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  name text not null,
  position text not null default '',
  team text not null references public.teams(name) on update cascade on delete cascade,
  linkedin text,
  email text,
  instagram text,
  twitter text,
  github text,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null default '',
  image text,
  status text not null default 'upcoming' check (status in ('upcoming', 'past')),
  date date not null default current_date,
  tags text[] not null default '{}',
  "isNew" boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.teams enable row level security;
alter table public.members enable row level security;
alter table public.events enable row level security;

drop policy if exists "Allow public read teams" on public.teams;
create policy "Allow public read teams"
on public.teams
for select
to anon, authenticated
using (true);

drop policy if exists "Allow public read members" on public.members;
create policy "Allow public read members"
on public.members
for select
to anon, authenticated
using (true);

drop policy if exists "Allow public read events" on public.events;
create policy "Allow public read events"
on public.events
for select
to anon, authenticated
using (true);
